#!/usr/bin/env node
// cochange.test.cjs — checks for the co-change overlay (AP12).
// Run: node cochange.test.cjs [section]   sections: regeln inkrementell echt paket
//
// `regeln` and `inkrementell` build a synthetic git repo whose commits are known, so
// weights, decay and exclusions can be checked to the digit. `echt` and `paket` run
// against orch_tui. Vault: backlog/nord/implementierer-paket-aus-dem-graphen (AP12).

const fs = require("fs");
const os = require("os");
const path = require("path");
const crypto = require("crypto");
const { execFileSync } = require("child_process");

const CC = path.join(__dirname, "cochange.cjs");
const WP = path.join(__dirname, "work-package.cjs");
const REPO = process.env.WP_TEST_REPO || path.join(os.homedir(), "00_projects/169_orch_tui/orch_tui");
const cc = require(CC);

let failed = 0;
function check(name, ok, detail) {
  if (!ok) failed++;
  console.log(`${ok ? "ok  " : "FAIL"} ${name}${ok || !detail ? "" : "  -> " + detail}`);
}
const near = (a, b) => Math.abs(a - b) < 1e-6;
const DAY = 86400;

// ---- synthetic repo -------------------------------------------------------------
// a/a.go: A1, A2, A3   b/b.go: B1   c/c.go: C1   gen/x.pb.go: G1 (generated)
function goFile(pkg, funcs, tag) {
  return `package ${pkg}\n\n` + funcs.map((f) => `func ${f}() int {\n\treturn ${tag[f] || 0}\n}\n`).join("\n");
}
function mkRepo() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "cochange-test-"));
  const g = (...a) => execFileSync("git", ["-C", root, ...a], { encoding: "utf8" });
  g("init", "-q", "-b", "main");
  g("config", "user.email", "t@t"); g("config", "user.name", "t");
  const state = { A1: 0, A2: 0, A3: 0, B1: 0, C1: 0, G1: 0, D1: 0, D2: 0, D3: 0 };
  const write = () => {
    fs.mkdirSync(path.join(root, "a"), { recursive: true });
    fs.mkdirSync(path.join(root, "b"), { recursive: true });
    fs.mkdirSync(path.join(root, "c"), { recursive: true });
    fs.mkdirSync(path.join(root, "d"), { recursive: true });
    fs.mkdirSync(path.join(root, "gen"), { recursive: true });
    fs.writeFileSync(path.join(root, "a/a.go"), goFile("a", ["A1", "A2", "A3"], state));
    fs.writeFileSync(path.join(root, "b/b.go"), goFile("b", ["B1"], state));
    fs.writeFileSync(path.join(root, "c/c.go"), goFile("c", ["C1"], state));
    fs.writeFileSync(path.join(root, "d/d.go"), goFile("d", ["D1", "D2", "D3"], state));
    fs.writeFileSync(path.join(root, "gen/x.pb.go"), "// Code generated by protoc-gen-go. DO NOT EDIT.\n" + goFile("gen", ["G1"], state));
  };
  const commit = (names, daysAgo, msg) => {
    for (const n of names) state[n]++;
    write();
    const date = `@${NOW - daysAgo * DAY} +0000`;
    g("add", "-A", "--", ".");
    execFileSync("git", ["-C", root, "commit", "-q", "-m", msg], {
      env: { ...process.env, GIT_AUTHOR_DATE: date, GIT_COMMITTER_DATE: date } });
    return g("rev-parse", "HEAD").trim();
  };
  return { root, g, state, commit, write };
}
const NOW = 1790000000;

// A fake graph.json with the node ids the overlay must key on.
function writeGraph(root) {
  const node = (id, label, file, line) => ({ id, label, source_file: file, source_location: `L${line}`, file_type: "code" });
  const nodes = [
    node("a_a1", "A1()", "a/a.go", 3), node("a_a2", "A2()", "a/a.go", 7), node("a_a3", "A3()", "a/a.go", 11),
    node("b_b1", "B1()", "b/b.go", 3), node("c_c1", "C1()", "c/c.go", 3), node("gen_g1", "G1()", "gen/x.pb.go", 4),
    node("d_d1", "D1()", "d/d.go", 3), node("d_d2", "D2()", "d/d.go", 7), node("d_d3", "D3()", "d/d.go", 11),
  ];
  fs.mkdirSync(path.join(root, "graphify-out"), { recursive: true });
  fs.writeFileSync(path.join(root, "graphify-out/graph.json"),
    JSON.stringify({ nodes, links: [{ source: "a_a1", target: "a_a2", relation: "calls", confidence: "EXTRACTED" }], built_at_commit: "x" }));
}

const SECTIONS = {
  regeln() {
    const r = mkRepo();
    r.commit(["A1", "A2", "A3", "B1", "C1", "G1", "D1", "D2", "D3"], 900, "initial"); // > maxSymbols -> skipped
    const c1 = r.commit(["A1", "B1"], 10, "c1");
    const c2 = r.commit(["A1", "B1"], 400, "c2 (old, backdated)");
    r.commit(["A1", "A2"], 1, "c3");
    r.commit(["A1", "A2", "A3", "B1", "C1"], 2, "c4 big"); // 5 symbols > maxSymbols 4 -> skipped
    r.commit(["A2", "G1"], 3, "c5 generated");
    // A branch commit B1+C1 merged with --no-ff: the branch commit counts, the merge not.
    r.g("checkout", "-q", "-b", "side");
    const side = r.commit(["B1", "C1"], 5, "side");
    r.g("checkout", "-q", "main");
    const mdate = `@${NOW - 4 * DAY} +0000`;
    execFileSync("git", ["-C", r.root, "merge", "-q", "--no-ff", "side", "-m", "merge"],
      { env: { ...process.env, GIT_AUTHOR_DATE: mdate, GIT_COMMITTER_DATE: mdate } });
    const merge = r.g("rev-parse", "HEAD").trim();
    writeGraph(r.root);
    const graphHash = crypto.createHash("sha256").update(fs.readFileSync(path.join(r.root, "graphify-out/graph.json"))).digest("hex");

    const ov = cc.build(r.root, { now: NOW, halfLifeDays: 180, maxSymbols: 4, minCount: 2 });
    const onDisk = JSON.parse(fs.readFileSync(path.join(r.root, "graphify-out/cochange.json"), "utf8"));
    check("regeln: overlay is written next to graph.json", onDisk.pairs && Object.keys(onDisk.pairs).length > 0);
    check("regeln: graph.json is untouched", graphHash === crypto.createHash("sha256")
      .update(fs.readFileSync(path.join(r.root, "graphify-out/graph.json"))).digest("hex"));
    check("regeln: the merge commit is not counted", !(merge in ov.commits), Object.keys(ov.commits).join(","));
    check("regeln: the merged branch commit is counted", side in ov.commits);
    check("regeln: c1 lists A1 and B1 by file#name", JSON.stringify([...ov.commits[c1].syms].sort()) === '["a/a.go#A1","b/b.go#B1"]',
      JSON.stringify(ov.commits[c1]));

    const w = (d) => Math.pow(0.5, d / 180);
    const p = cc.pair(ov, "a_a1", "b_b1");
    check("regeln: pair A1|B1 exists", Boolean(p));
    // c1 (10 d) and c2 (400 d); c4 and the initial commit are over maxSymbols.
    check("regeln: support decays with age", p && near(p.support, w(10) + w(400)), p && `${p.support} vs ${w(10) + w(400)}`);
    check("regeln: count is the raw number of commits", p && p.count === 2, p && String(p.count));
    // A1 alone: c1, c2, c3; B1 alone: c1, c2, side.
    const sA1 = w(10) + w(400) + w(1), sB1 = w(10) + w(400) + w(5);
    check("regeln: confidence A1->B1", p && near(p.confidence["a_a1"], (w(10) + w(400)) / sA1), p && JSON.stringify(p.confidence));
    check("regeln: confidence B1->A1", p && near(p.confidence["b_b1"], (w(10) + w(400)) / sB1));
    const total = ov.totalSupport;
    check("regeln: lift = P(AB) / (P(A) P(B))", p && near(p.lift, (p.support * total) / (sA1 * sB1)), p && String(p.lift));
    check("regeln: timestamp is the newest co-change", p && p.last === NOW - 10 * DAY, p && String(p.last));
    check("regeln: generated code forms no pair", !cc.pair(ov, "a_a2", "gen_g1"));
    check("regeln: a commit over maxSymbols forms no pair", !cc.pair(ov, "a_a3", "c_c1"));
    // A pair is keyed once, in id order.
    check("regeln: pair lookup is symmetric", cc.pair(ov, "b_b1", "a_a1") === p);

    // Fallback: C1 co-changed once (side), under minCount -> package level answers.
    const nC = cc.neighbours(ov, "c_c1");
    check("regeln: thin symbol support falls back to package level",
      nC.length > 0 && nC.every((n) => n.level === "package") && nC.some((n) => n.package === "b"), JSON.stringify(nC));
    const nA = cc.neighbours(ov, "a_a1");
    check("regeln: enough support answers on symbol level", nA.some((n) => n.level === "symbol" && n.id === "b_b1"), JSON.stringify(nA));
    check("regeln: a pair with a structural edge is marked", nA.every((n) => n.id !== "a_a2" || n.structural === true)
      && nA.some((n) => n.id === "b_b1" && n.structural === false), JSON.stringify(nA));
    fs.rmSync(r.root, { recursive: true, force: true });
  },

  inkrementell() {
    const r = mkRepo();
    r.commit(["A1", "B1"], 10, "c1");
    r.commit(["A1", "B1"], 9, "c2");
    writeGraph(r.root);
    const first = cc.build(r.root, { now: NOW, halfLifeDays: 180, maxSymbols: 4, minCount: 2 });
    const c3 = r.commit(["A1", "C1"], 1, "c3");
    const up = cc.update(r.root, { now: NOW, halfLifeDays: 180, maxSymbols: 4, minCount: 2 });
    check("inkrementell: update adds exactly the new commit",
      Object.keys(up.commits).length === Object.keys(first.commits).length + 1 && c3 in up.commits);
    check("inkrementell: update result equals a full rebuild",
      JSON.stringify(up.pairs) === JSON.stringify(cc.build(r.root, { now: NOW, halfLifeDays: 180, maxSymbols: 4, minCount: 2 }).pairs));
    let spawned = 0;
    const again = cc.update(r.root, { now: NOW, halfLifeDays: 180, maxSymbols: 4, minCount: 2, onCommit: () => spawned++ });
    check("inkrementell: a second update touches no commit", spawned === 0 && Object.keys(again.commits).length === Object.keys(up.commits).length);
    fs.rmSync(r.root, { recursive: true, force: true });
  },

  echt() {
    const t0 = Date.now();
    const ov = cc.build(REPO, {});
    const secs = (Date.now() - t0) / 1000;
    check("echt: full build on orch_tui under 120 s", secs < 120, `${secs}s`);
    check("echt: 94cab77 is in the overlay with Deliver", Object.entries(ov.commits)
      .some(([sha, c]) => sha.startsWith("94cab77") && c.syms.includes("internal/agent/agent.go#Deliver")));
    const p = cc.pair(ov, "agent_agent_deliver", "agent_agent_interrupt");
    check("echt: Deliver|Interrupt co-change", p && p.count >= 1, JSON.stringify(p));
    check("echt: every pair key is a graph node id", (() => {
      const ids = new Set(JSON.parse(fs.readFileSync(path.join(REPO, "graphify-out/graph.json"), "utf8")).nodes.map((n) => n.id));
      return Object.keys(ov.pairs).every((k) => k.split("|").every((id) => ids.has(id)));
    })());
  },

  paket() {
    const wp = require(WP);
    const q = { symbols: ["Deliver"], terms: [], subsystems: ["agent"] };
    const on = wp.buildPackage({ repo: REPO, questions: q });
    const off = wp.buildPackage({ repo: REPO, questions: q, cochange: false });
    const viaCC = (pkg) => [...pkg.tiers.wahrscheinlich, ...pkg.tiers.pruefen].filter((i) => i.via === "cochange");
    check("paket: co-change neighbours reach the package", viaCC(on).length > 0);
    check("paket: --no-cochange leaves them out", viaCC(off).length === 0);
    check("paket: co-change items sit in pruefen", viaCC(on).every((i) => on.tiers.pruefen.includes(i)));
    check("paket: a co-change pair without a structural edge is named in the hints",
      on.hints.some((h) => /Co-Change ohne Strukturkante/.test(h)), JSON.stringify(on.hints.slice(0, 3)));
    // Deliver and Interrupt co-change, and both are change targets: no hint for that pair.
    const both = wp.buildPackage({ repo: REPO, questions: { symbols: ["Deliver", "Interrupt"], terms: [], subsystems: ["agent"] } });
    check("paket: no hint for a pair whose ends are both in aendern",
      !both.hints.some((h) => /Deliver\(\) <-> \.Interrupt|Interrupt\(\) <-> \.Deliver/.test(h)), JSON.stringify(both.hints));
  },
};

const only = process.argv[2];
for (const [name, fn] of Object.entries(SECTIONS)) {
  if (only && only !== name) continue;
  try { fn(); } catch (e) { check(`${name}: threw`, false, e.stack.split("\n").slice(0, 3).join(" | ")); }
}
console.log(failed ? `\n${failed} FAILED` : "\nall ok");
process.exit(failed ? 1 : 0);
